### ISSUE TITLE
VS 2013 Crashes after installing latest version.

### ISSUE THREAD

**Issue by subramn** [lkytal/SmoothScroll#4]
Hi,

I have installed the latest version after wards not able to open Visual Studio 2013 empty windows comes. after removing the extension visual studio 2013 opens fine.

Thanks

**Comment by lkytal** [comment]
Could you please provide the error message?

**Comment by subramn** [comment]
When i opened Visual Studio 2013 with update 5 after installing the following error is logged in event viewer


Faulting application name: devenv.exe, version: 12.0.40629.0, time stamp: 0x5590c8a4
Faulting module name: KERNELBASE.dll, version: 6.1.7601.23392, time stamp: 0x56eb30d1
Exception code: 0xe0434352
Fault offset: 0x0000c54f
Faulting process id: 0x1d2c
Faulting application start time: 0x01d19b584127f86b
Faulting application path: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 819be8ad-074b-11e6-813e-00059a3c7a00

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException
Stack:
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(System.Object, System.Object[], System.Object[])
   at System.Delegate.DynamicInvokeImpl(System.Object[])
   at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
   at System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ScrollableControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.ContainerControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.UserControl.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr)

I tried in an another machine with Visual Studio 2013 same error.

**Comment by lkytal** [comment]
Did version 2.0.4 fix this for you?

**Comment by subramn** [comment]
Yes fixed thank you for the help and it was neat.
